---
# Style configuration
extends:
  - airbnb-base
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - react-app
  - prettier
  - prettier/react
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
plugins:
  - react
  - prettier
  - react-hooks
  - "@typescript-eslint/eslint-plugin"
  - eslint-plugin-tsdoc
  - import
  - jsx-a11y
rules:
  tsdoc/syntax: warn
  react/display-name: off
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  import/no-named-as-default: off
  import/no-named-as-default-member: off
  import/prefer-default-export: off
  no-underscore-dangle: off
  import/default: off
  import/no-extraneous-dependencies: error
  import/no-unresolved: error
  react/prop-types: off
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  import/extensions:
    - warn
    - js: never
      ts: never
      json: always
      scss: always

  # Prettier config
  prettier/prettier:
    - error
    - semi: true
      endOfLine: auto
      quoteProps: consistent

overrides:
  # Disable warning `require`/console-log on Node-js files
  - files:
      - node.api.js
      - static.config.js
    rules:
      "@typescript-eslint/no-var-requires": off

# ESLint Project Settings
settings:
  react:
    version: detect
  import/parsers:
    "@typescript-eslint/parser":
      - ".ts"
      - ".tsx"
  import/resolver:
    typescript:
      alwaysTryTypes: true
      directory": ./*/tsconfig.json
    node:
      paths:
        - src
      extensions:
        - ".ts"
        - ".tsx"
env:
  es6: true
  node: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2019
  sourceType: module
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
    modules: true
