# Reroute all App URLs under the dynamic path pattern to the React app
[[redirects]]
  from = "/app/*"
  to = "/app.html"
  status = 200

# Redirect domain aliases to primary domain
[[redirects]]
  from = "https://aut-bot.com/*"
  to = "https://archit.us/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.aut-bot.com/*"
  to = "https://archit.us/:splat"
  status = 301
  force = true

# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://architus.netlify.com/*"
  to = "https://archit.us/:splat"
  status = 301
  force = true

[build]
  # Disable type checking on building to save time on Netlify
  command = "yarn build --no-type-check"
  # Base environment for canary and production
  [build.environment]
    APP_NAME = "Architus Canary"
    SITE_ROOT = "https://develop.archit.us"
    BUILD_LOCATION = "remote"
    NODE_ENV = "production"

[context.production]
  command = "yarn build"
  # Overrides for production
  [context.production.environment]
    APP_NAME = "Architus"
    SITE_ROOT = "https://archit.us"
    PRODUCTION = "true"

