export const TOKEN_EXCHANGE = "TOKEN_EXCHANGE";
export const IDENTIFY_SESSION = "IDENTIFY_SESSION";
export const GET_GUILDS = "GET_GUILDS";
export const GET_GUILD_COUNT = "GET_GUILD_COUNT";
export const GET_RESPONSES = "GET_RESPONSES";
