export const TOKEN_EXCHANGE = "TOKEN_EXCHANGE";
export const IDENTIFY_SESSION = "IDENTIFY_SESSION";
export const GET_GUILDS = "GET_GUILDS";
export const GET_RESPONSES = "GET_RESPONSES";
export const ADD_RESPONSE = "ADD_RESPONSE";
export const EDIT_RESPONSE = "EDIT_RESPONSE";
export const DELETE_RESPONSE = "DELETE_RESPONSE";
