---
extends:
  - "../.eslintrc.yml"

rules:
  # GraphQL
  # From https://github.com/cometkim/gatsby-plugin-typegen#eslint
  graphql/template-strings:
    - error
    - env: relay
      tagName: graphql
      schemaJsonFilepath: 'src/__generated__/gatsby-introspection.json'

overrides:
  # Disable warning `require` on build files
  - files:
      - src/build/*
      - gatsby-*
    rules:
      "@typescript-eslint/no-var-requires": off

# ESLint Project Settings
settings:
  import/resolver:
    typescript:
      alwaysTryTypes: true
      directory": ./tsconfig.json

ignorePatterns:
  - "src/__generated__/*"
