---
# Style configuration
extends:
  - airbnb-base
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - react-app
  - prettier
  - prettier/react
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
plugins:
  - react
  - prettier
  - react-hooks
  - "@typescript-eslint/eslint-plugin"
  - eslint-plugin-tsdoc
  - import
  - jsx-a11y
  - graphql
rules:
  tsdoc/syntax: warn
  react/display-name: off
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  import/no-named-as-default: off
  import/no-named-as-default-member: off
  import/prefer-default-export: off
  no-underscore-dangle: 0
  import/default: off
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
  import/no-unresolved: off
  import/order:
    - error
    - groups:
      - ["external", "builtin"]
      - ["index", "sibling", "parent", "internal", "object"]
      pathGroups:
        - pattern: "@(?:app)|(?:docs)|(?:lib)|(?:design)/**"
          group: "internal"
      pathGroupsExcludedImportTypes:
        - builtin
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true
  react/prop-types: off
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  import/extensions:
    - warn
    - js: never
      ts: never
      json: always
      scss: always
      css: always
      svg: always
      woff: always
      woff2: always

  # GraphQL
  # From https://github.com/cometkim/gatsby-plugin-typegen#eslint
  graphql/template-strings:
    - error
    - env: relay
      tagName: graphql
      schemaJsonFilepath: 'src/__generated__/gatsby-introspection.json'

  # Prettier config
  prettier/prettier:
    - error
    - semi: true
      endOfLine: auto

overrides:
  # Disable warning `require`/console-log on build files
  - files:
      - src/build/*
      - gatsby-*
    rules:
      "@typescript-eslint/no-var-requires": off

# ESLint Project Settings
settings:
  react:
    version: detect
  import/parsers:
    "@typescript-eslint/parser":
      - ".ts"
      - ".tsx"
  import/resolver:
    typescript:
      alwaysTryTypes: true
      directory": ./tsconfig.json
env:
  es6: true
  node: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2019
  sourceType: module
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
    modules: true
ignorePatterns:
  - "src/__generated__/*"
